export default [
	{ name: 'claude-opus-4-5-migration', type: 'codebase', description: 'Migrate prompts/workflows to Claude Opus 4.5 standards.', instructionPath: 'models/claude-code/plugins/claude-opus-4-5-migration/skills/claude-opus-4-5-migration/SKILL.md' },
	{ name: 'claude-frontend-design', type: 'custom', description: 'Front-end design workflow with stronger visual direction.', instructionPath: 'models/claude-code/plugins/frontend-design/skills/frontend-design/SKILL.md' },
	{ name: 'claude-writing-rules', type: 'custom', description: 'Define and maintain Hookify rule-writing patterns.', instructionPath: 'models/claude-code/plugins/hookify/skills/writing-rules/SKILL.md' },
	{ name: 'claude-agent-development', type: 'codebase', description: 'Create plugin agents with proper triggers and prompts.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/agent-development/SKILL.md' },
	{ name: 'claude-command-development', type: 'custom', description: 'Build slash command definitions for Claude plugins.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/command-development/SKILL.md' },
	{ name: 'claude-hook-development', type: 'custom', description: 'Build and validate lifecycle hooks in plugin workflows.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/hook-development/SKILL.md' },
	{ name: 'claude-mcp-integration', type: 'custom', description: 'Integrate and configure MCP servers/tools safely.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/mcp-integration/SKILL.md' },
	{ name: 'claude-plugin-settings', type: 'filesystem', description: 'Add robust plugin settings schemas and handlers.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/plugin-settings/SKILL.md' },
	{ name: 'claude-plugin-structure', type: 'codebase', description: 'Scaffold plugin folder structure and conventions.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/plugin-structure/SKILL.md' },
	{ name: 'claude-skill-development', type: 'custom', description: 'Create high-quality skill packages and docs.', instructionPath: 'models/claude-code/plugins/plugin-dev/skills/skill-development/SKILL.md' },
	{ name: 'codex-babysit-pr', type: 'codebase', description: 'Monitor PR lifecycle, CI, and review feedback continuously.', instructionPath: 'models/codex/.codex/skills/babysit-pr/SKILL.md' },
	{ name: 'codex-test-tui', type: 'terminal', description: 'Run and validate Codex TUI behavior end-to-end.', instructionPath: 'models/codex/.codex/skills/test-tui/SKILL.md' },
	{ name: 'codex-skill-creator', type: 'custom', description: 'Create or improve Codex skills with repeatable workflow.', instructionPath: 'models/codex/codex-rs/skills/src/assets/samples/skill-creator/SKILL.md' },
	{ name: 'codex-skill-installer', type: 'search', description: 'Install curated or remote skills into Codex environment.', instructionPath: 'models/codex/codex-rs/skills/src/assets/samples/skill-installer/SKILL.md' },
	{ name: 'gemini-code-reviewer', type: 'codebase', description: 'Review local and PR changes with structured quality checks.', instructionPath: 'models/gemini-cli/.gemini/skills/code-reviewer/SKILL.md' },
	{ name: 'gemini-docs-changelog', type: 'filesystem', description: 'Generate release changelog files in project format.', instructionPath: 'models/gemini-cli/.gemini/skills/docs-changelog/SKILL.md' },
	{ name: 'gemini-docs-writer', type: 'filesystem', description: 'Write/edit docs under project documentation standards.', instructionPath: 'models/gemini-cli/.gemini/skills/docs-writer/SKILL.md' },
	{ name: 'gemini-pr-address-comments', type: 'codebase', description: 'Address PR review comments with structured triage flow.', instructionPath: 'models/gemini-cli/.gemini/skills/pr-address-comments/SKILL.md' },
	{ name: 'gemini-pr-creator', type: 'codebase', description: 'Create PRs following repository policies and templates.', instructionPath: 'models/gemini-cli/.gemini/skills/pr-creator/SKILL.md' },
	{ name: 'gemini-greeter', type: 'custom', description: 'Simple example skill for greeting behavior.', instructionPath: 'models/gemini-cli/packages/cli/src/commands/extensions/examples/skills/skills/greeter/SKILL.md' },
	{ name: 'gemini-skill-creator', type: 'custom', description: 'Built-in Gemini skill creation guidance.', instructionPath: 'models/gemini-cli/packages/core/src/skills/builtin/skill-creator/SKILL.md' },
	{ name: 'gemini-pirate-skill', type: 'custom', description: 'Pirate speaking style sample skill.', instructionPath: 'models/gemini-cli/packages/sdk/test-data/skills/pirate-skill/SKILL.md' },
	{ name: 'qwen-pr-review', type: 'codebase', description: 'Review PRs with code analysis and smoke-testing flow.', instructionPath: 'models/qwen-code/.qwen/skills/pr-review/SKILL.md' },
	{ name: 'qwen-terminal-capture', type: 'terminal', description: 'Automate terminal UI screenshots and CLI visual tests.', instructionPath: 'models/qwen-code/.qwen/skills/terminal-capture/SKILL.md' },
	{ name: 'qwen-synonyms', type: 'search', description: 'Generate synonyms and alternatives for text prompts.', instructionPath: 'models/qwen-code/packages/cli/src/commands/extensions/examples/skills/skills/synonyms/SKILL.md' }
] as const;
